version: '3.8'

services:
  app:
    container_name: solar-energy
    image: solar-energy
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
