export const userMock = {
  user: 'teste@teste.com',
  roles: [],
  token:
    'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBVVJPUkEiLCJhdWQiOiJBVVJPUkEiLCJleHAiOjMwMjc2NTMzNTAsInJvbGVzIjpbIlBBQ1NOR19ESUNPTV9CVUxLREFUQSIsIlBBQ1NOR19ESUNPTV9XQURPIiwiUEFDU05HX0RJQ09NX1FJRE8iLCJQQUNTTkdfQ09ORklHVVJBVElPTiIsIlBBQ1NOR19OT0RFX0NPTlRST0wiLCJQQUNTTkdfU0VSSUVTX01JR1JBVElPTiIsIlBBQ1NOR19TRVJJRVNfUkVNT1ZBTCJdLCJwcmVmZXRjaHJvbGVzIjpbXSwidXNlciI6InVzZXJ0ZXN0ZSJ9.8a_ZdpxfM1_rU-ekCaZnefGFsJVq2_LetC5yBD_80SE',
};

export const loginRequestMock = {
  email: 'usuario@usuario.com',
  password: 'password',
};

